// <auto-generated />
using System;
using DesafioTecnicoSTi3.data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioTecnicoSTi3.data.Migrations
{
    [DbContext(typeof(DesafioTecnicoSTi3Context))]
    [Migration("20210729153228_Pedido")]
    partial class Pedido
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("DesafioTecnicoSTi3.data.Entidades.Clientes", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("cnpj")
                        .HasColumnType("varchar(100)");

                    b.Property<long>("codigo_cliente")
                        .HasColumnType("bigint");

                    b.Property<string>("cpf")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("dataNascimento")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("email")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("nome")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("razaoSocial")
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("DesafioTecnicoSTi3.data.Entidades.Configuracoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("UrlAPI")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Configuracoes");
                });

            modelBuilder.Entity("DesafioTecnicoSTi3.data.Entidades.EnderecoEntrega", b =>
                {
                    b.Property<long>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("bairro")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("cep")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("cidade")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("complemento")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("endereco")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("estado")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("id")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("numero")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("referencia")
                        .HasColumnType("varchar(100)");

                    b.HasKey("codigo");

                    b.ToTable("EnderecoEntregas");
                });

            modelBuilder.Entity("DesafioTecnicoSTi3.data.Entidades.Item", b =>
                {
                    b.Property<long>("codigo_item")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("Pedidocod_pedido")
                        .HasColumnType("bigint");

                    b.Property<string>("id")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("idProduto")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("nome")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("quantidade")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("valorUnitario")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("codigo_item");

                    b.HasIndex("Pedidocod_pedido");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("DesafioTecnicoSTi3.data.Entidades.Pagamento", b =>
                {
                    b.Property<long>("cod_pgto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("Pedidocod_pedido")
                        .HasColumnType("bigint");

                    b.Property<string>("codigo")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("id")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("nome")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("parcela")
                        .HasColumnType("int(30)");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("cod_pgto");

                    b.HasIndex("Pedidocod_pedido");

                    b.ToTable("Pagamento");
                });

            modelBuilder.Entity("DesafioTecnicoSTi3.data.Entidades.Pedido", b =>
                {
                    b.Property<long>("cod_pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("clienteid")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("dataAlteracao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("dataCriacao")
                        .HasColumnType("datetime");

                    b.Property<double>("desconto")
                        .HasColumnType("double");

                    b.Property<long?>("enderecoEntregacodigo")
                        .HasColumnType("bigint");

                    b.Property<double>("frete")
                        .HasColumnType("double");

                    b.Property<string>("id")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("numero")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("status")
                        .HasColumnType("varchar(20)");

                    b.Property<double>("subTotal")
                        .HasColumnType("double");

                    b.Property<double>("valorTotal")
                        .HasColumnType("double");

                    b.HasKey("cod_pedido");

                    b.HasIndex("clienteid");

                    b.HasIndex("enderecoEntregacodigo");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("DesafioTecnicoSTi3.data.Entidades.Item", b =>
                {
                    b.HasOne("DesafioTecnicoSTi3.data.Entidades.Pedido", null)
                        .WithMany("itens")
                        .HasForeignKey("Pedidocod_pedido");
                });

            modelBuilder.Entity("DesafioTecnicoSTi3.data.Entidades.Pagamento", b =>
                {
                    b.HasOne("DesafioTecnicoSTi3.data.Entidades.Pedido", null)
                        .WithMany("pagamento")
                        .HasForeignKey("Pedidocod_pedido");
                });

            modelBuilder.Entity("DesafioTecnicoSTi3.data.Entidades.Pedido", b =>
                {
                    b.HasOne("DesafioTecnicoSTi3.data.Entidades.Clientes", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteid");

                    b.HasOne("DesafioTecnicoSTi3.data.Entidades.EnderecoEntrega", "enderecoEntrega")
                        .WithMany()
                        .HasForeignKey("enderecoEntregacodigo");

                    b.Navigation("cliente");

                    b.Navigation("enderecoEntrega");
                });

            modelBuilder.Entity("DesafioTecnicoSTi3.data.Entidades.Pedido", b =>
                {
                    b.Navigation("itens");

                    b.Navigation("pagamento");
                });
#pragma warning restore 612, 618
        }
    }
}
